@host = http://localhost:3000
@jwt = <JWT_TOKEN>

### Регистрация пользователя
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "fullName": "Иванов Иван Иванович",
  "email": "another@example.com",
  "password": "123456",
  "birthDate": "2000-07-12"
}

### Вход пользователя
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "ivan@example.com",
  "password": "123456"
}

### Заблокировать пользователя по ID
PATCH http://localhost:3000/api/users/block/2
Authorization: Bearer {{jwt}}

### Разблокировать пользователя по ID
PATCH http://localhost:3000/api/users/unblock/2
Authorization: Bearer {{jwt}}

### Получение всех пользователей (admin)
GET {{host}}/api/users/
Authorization: Bearer {{jwt}}





