@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzOTI1MTY4LCJleHAiOjE3NjM5Mjg3Njh9.zctAK3OSazsO_0MBwHoI4BgXfcXjnHjiQCs8ERZzvXI

### Регистрация пользователя
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "fullName": "Мурзов Альберт Валерьевич",
  "email": "another@example.com",
  "password": "123456",
  "birthDate": "2000-07-12"
}

### Вход пользователя
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "ivan@example.com",
  "password": "123456"
}

### Заблокировать пользователя по ID
PATCH http://localhost:3000/api/users/block/2
Authorization: Bearer {{jwt}}

### Разблокировать пользователя по ID
PATCH http://localhost:3000/api/users/unblock/2
Authorization: Bearer {{jwt}}


### Получение всех пользователей (admin)
GET {{host}}/api/users/
Authorization: Bearer {{jwt}}





